name = "claudusbridge-bugs"
main = "src/index.js"
compatibility_date = "2024-09-23"
account_id = "a76d552503f1beccca1152f6796c4e7d"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "claudusbridge-bugs"
database_id = "4f655cbb-150d-4cb8-b28e-2467f57c84a3"

[vars]
CORS_ORIGIN = "*"
