name = "claudusbridge-bugs"
main = "src/index.js"
compatibility_date = "2024-09-23"
account_id = "083a587f75d79803239a49f08e043f65"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "claudusbridge-bugs"
database_id = "8d52c8fc-160f-489a-9307-28236bfc0e0a"

[vars]
CORS_ORIGIN = "*"
